sonar.organization=eppcage
sonar.projectKey=EPPCAGE_gesproc2.0
sonar.projectName=gesproc2.0
sonar.sources=.
sonar.exclusions=**/node_modules/**,functions/node_modules/**,**/*.min.js,**/dist/**
sonar.language=js
sonar.sourceEncoding=UTF-8