const {chromium}=require('playwright');
const {readFileSync}=require('node:fs');
const assert=require('node:assert/strict');
(async()=>{
  const html=readFileSync('processos.html','utf8');
  const browser=await chromium.launch({headless:true});
  try{
    const page=await browser.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));
    const start=html.indexOf('<div id="page-riscos"');
    await page.setContent(html.slice(html.lastIndexOf('<style>',start),html.indexOf('<div id="page-faq"',start))+'<div id="risco-list"></div><div id="risco-matrix"></div>');
    await page.addScriptTag({path:'src/shared/riscos.js'});
    await page.addScriptTag({path:'src/shared/relatorio-executivo-style.js'});
    await page.evaluate(()=>{
      window.esc=value=>String(value ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
      window.usuarioLogado={perfil:'ep',email:'ep@example.org'};window.isEP=()=>usuarioLogado.perfil==='ep';
      window.crypto.randomUUID=()=> 'risco-teste-1';
      window.processos=[{id:1,arq_id:'p',nome:'Auditar',ent:{riscos:[{desc:'Prazo legal',prob:'Alta',imp:'Critico'},{desc:'Dados ausentes',prob:'Media',imp:'Alto',status_tratamento:'em_tratamento',prazo_tratamento:'2020-01-01'}]}},{id:2,arq_id:'q',nome:'Controlar',ent:{riscos:[{desc:'Outro risco',prob:'Baixa',imp:'Baixo'}]}}];
      window.ARQUITETURA=[{nome:'Auditoria',processos:[{id:'p',nome:'Auditar',area:'Auditoria'}]},{nome:'Controle',processos:[{id:'q',nome:'Controlar',area:'Controle'}]}];
      window.curProc=processos[0];window.fbReady=()=>true;window._fbLoadedAt=1;window.fbSaveAll=async()=>{window.saved=JSON.parse(JSON.stringify(processos));};
      window.fbAutoSave=()=>{};window.toast=()=>{};window.pbBadge=value=>value;window.ibBadge=value=>value;
      window.rRiscoMatriz=()=>'';
      window.abrirInfoMeusProc=(id,pid)=>{window.infoProcess=pid;};
      window.actualizarRiscoUI=()=>{};
    });
    await page.addScriptTag({path:'src/processos/riscos-module.js'});
    await page.addScriptTag({content:['rRiscoList','atualizarRiscoUI','_renderRiscosCard'].map(name=>html.match(new RegExp('function '+name+'\\([^]*?\\n}'))[0]).join('\n')});
    await page.evaluate(()=>rRiscos());
    assert.equal(await page.locator('.risk-item').count(),3);
    const prob=page.locator('.risk-filter').filter({has:page.locator('#riscos-prob')});
    await prob.locator('summary').click();await prob.getByRole('checkbox',{name:'Alta',exact:true}).check();assert.equal(await page.locator('.risk-item').count(),1);
    await prob.getByRole('checkbox',{name:'Média',exact:true}).check();assert.equal(await page.locator('.risk-item').count(),2);
    await prob.getByRole('checkbox',{name:'Média',exact:true}).uncheck();await prob.locator('summary').click();
    const area=page.locator('.risk-filter').filter({has:page.locator('#riscos-area')});
    await area.locator('summary').click();await area.getByRole('checkbox',{name:'Controle',exact:true}).check();assert.equal(await page.locator('.risk-item').count(),0);
    await area.getByRole('checkbox',{name:'Auditoria',exact:true}).check();assert.equal(await page.locator('.risk-item').count(),1);
    await area.getByRole('checkbox',{name:'Controle',exact:true}).uncheck();await area.locator('summary').click();
    await page.getByRole('button',{name:'Registrar tratamento'}).click();
    await page.selectOption('#risk-status','tratado');await page.selectOption('#risk-type','Mitigado');await page.fill('#risk-action','Controle implantado');
    await page.getByRole('button',{name:'Salvar tratamento'}).click();assert.match(await page.locator('#risk-save-error').innerText(),/evidência/);
    await page.fill('#risk-evidence','Testado e eficaz');await page.fill('#risk-owner','Maria');await page.fill('#risk-deadline','2026-10-10');
    await page.getByRole('button',{name:'Salvar tratamento'}).click();
    await page.waitForFunction(()=>!document.getElementById('risk-treatment-modal'));
    assert.equal(await page.evaluate(()=>saved[0].ent.riscos[0].status_tratamento),'tratado');
    assert.match(await page.locator('#risco-list').innerText(),/Tratado/);assert.match(await page.locator('#risco-list').innerText(),/Controle implantado/);
    await page.evaluate(()=>{document.getElementById('risco-list').innerHTML=_renderRiscosCard(processos[0].ent.riscos);});
    assert.match(await page.locator('#risco-list').innerText(),/Controle implantado/);
    await page.getByRole('button',{name:'Sobre o processo',exact:true}).click();assert.equal(await page.evaluate(()=>infoProcess),1);
    await page.evaluate(()=>{window.fbSaveAll=async()=>false;});
    await page.getByRole('button',{name:'Registrar tratamento'}).click();
    await page.selectOption('#risk-status','em_tratamento');
    await page.getByRole('button',{name:'Salvar tratamento'}).click();
    assert.match(await page.locator('#risk-save-error').innerText(),/Não foi possível salvar/);
    assert.equal(await page.evaluate(()=>processos[0].ent.riscos[0].status_tratamento),'tratado');
    await page.getByRole('button',{name:'Cancelar',exact:true}).click();
    await page.waitForFunction(()=>!document.getElementById('risk-treatment-modal'));
    await page.evaluate(()=>{usuarioLogado.perfil='dono';rRiscos();});assert.equal(await page.getByRole('button',{name:'Registrar tratamento'}).count(),0);
    const [report]=await Promise.all([page.waitForEvent('popup'),page.getByRole('button',{name:'Gerar relatório PDF',exact:true}).click()]);
    await report.waitForLoadState('domcontentloaded');
    assert.equal(await report.locator('.risk-report-item').count(),1);
    assert.equal(await report.locator('.cover-title').innerText(),'Relatório Executivo');
    assert.equal(await report.locator('.kpi').count(),7);
    assert.match(await report.locator('.risk-report-item').innerText(),/Controle implantado/);
    assert.match(await report.locator('.risk-report-item').innerText(),/Testado e eficaz/);
    assert.ok(!(await report.locator('body').innerText()).includes('Outro risco'));
    assert.match(await report.locator('.filters').innerText(),/Probabilidade: Alta/);
    const pdf=await report.pdf({format:'A4',printBackground:true});assert.equal(pdf.subarray(0,5).toString(),'%PDF-');
    await report.close();
    await page.evaluate(()=>riscosEdit('1',0));assert.equal(await page.locator('#risk-treatment-modal').count(),0);
    await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    assert.deepEqual(errors,[]);console.log('Riscos: filtros, matriz, tratamento, persistência, integração com mapeamento e permissões verificados.');
  }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
